name: ci
on:
  pull_request:
    paths:
      - "crates/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
  push:
    branches: [master]
    paths:
      - "crates/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
      - run: cargo xtask test
